version: '2'

services:
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_NAME=local
      #- ETCD_ROOT_PASSWORD=asdf
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - ./data:/etcd-data
  #myapp:
  #  image: 'YOUR_APPLICATION_IMAGE'
  #  networks:
  #    - app-tier
