#include ./default.env
#export

a: d u l

u:
	docker-compose -f docker-compose.yml up --build -d
d:
	docker-compose -f docker-compose.yml down -v
r:
	docker-compose -f docker-compose.yml restart
l:
	docker-compose -f docker-compose.yml logs -f
